[package]
name = "aiken"
description = "Cardano smart contract language and toolchain"
version = "1.0.0-alpha"
edition = "2021"
repository = "https://github.com/aiken-lang/aiken"
homepage = "https://github.com/aiken-lang/aiken"
license = "Apache-2.0"
authors = ["Lucas Rosa <x@rvcas.dev>", "Kasey White <kwhitemsg@gmail.com>", "KtorZ <matthias.benkort@gmail.com>"]
rust-version = "1.66.1"

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.8", features = ["derive", "wrap_help", "unicode"] }
hex = "0.4.3"
ignore = "0.4.20"
indoc = "2.0"
miette = { version = "5.5.0", features = ["fancy"] }
owo-colors = { version = "3.5.0", features = ["supports-colors"] }
pallas-addresses = "0.18.0"
pallas-codec = "0.18.0"
pallas-crypto = "0.18.0"
pallas-primitives = "0.18.0"
pallas-traverse = "0.18.0"
regex = "1.7.1"
serde_json = "1.0.94"
thiserror = "1.0.39"

aiken-lang = { path = "../aiken-lang", version = "1.0.0-alpha" }
aiken-lsp = { path = "../aiken-lsp", version = "1.0.0-alpha" }
aiken-project = { path = '../aiken-project', version = "1.0.0-alpha" }
uplc = { path = '../uplc', version = "1.0.0-alpha" }
