[package]
name = "aiken-project"
description = "Aiken project utilities"
version = "1.0.10-alpha"
edition = "2021"
repository = "https://github.com/aiken-lang/aiken/crates/project"
homepage = "https://github.com/aiken-lang/aiken"
license = "Apache-2.0"
authors = [
    "Lucas Rosa <x@rvcas.dev>",
    "Kasey White <kwhitemsg@gmail.com>",
    "KtorZ <matthias.benkort@gmail.com>",
]
rust-version = "1.66.1"

[dependencies]
askama = "0.12.0"
assert-json-diff = "2.0.2"
dirs = "4.0.0"
fslock = "0.2.1"
futures = "0.3.26"
hex = "0.4.3"
ignore = "0.4.20"
indexmap = "1.9.2"
itertools = "0.10.5"
miette = { version = "5.5.0", features = ["fancy"] }
minicbor = "0.19.1"
owo-colors = { version = "3.5.0", features = ["supports-colors"] }
pallas = "0.18.0"
pallas-traverse = "0.18.0"
petgraph = "0.6.3"
pulldown-cmark = { version = "0.9.2", default-features = false }
rayon = "1.7.0"
regex = "1.7.1"
reqwest = "0.11.14"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = { version = "1.0.94", features = ["preserve_order"] }
strip-ansi-escapes = "0.1.1"
thiserror = "1.0.39"
tokio = { version = "1.26.0", features = ["full"] }
toml = "0.7.2"
walkdir = "2.3.2"
zip = "0.6.4"

aiken-lang = { path = "../aiken-lang", version = "1.0.10-alpha" }
uplc = { path = '../uplc', version = "1.0.10-alpha" }


[dev-dependencies]
proptest = "1.1.0"
pretty_assertions = "1.3.0"
